/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 C:/Users/ADITYA/Desktop/coding/port/public/model.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, PerspectiveCamera, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/model.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Empty002" position={[0, 1.029, 0.004]} rotation={[0, -0.378, 0]}>
          <PerspectiveCamera name="Camera_1" makeDefault={false} far={1000} near={0.1} fov={31.891} position={[20.216, 7.792, 23.113]} rotation={[-0.184, 0.733, 0.124]} />
        </group>
        <directionalLight intensity={1270.38} decay={2} color="#ffdb83" position={[-2.801, 23.027, -5.789]} rotation={[-1.414, -0.164, 0.044]} target={nodes.Sun.target}>
          <primitive object={nodes.Sun.target} position={[0, 0, -1]} />
        </directionalLight>
        <mesh name="Cylinder" geometry={nodes.Cylinder.geometry} material={materials.bowl_P} position={[0, 1.739, 0]} rotation={[0.517, 0.171, -0.018]} scale={1.194} />
        <mesh name="Circle" geometry={nodes.Circle.geometry} material={materials.soup_P} position={[0.057, 3.026, 0.677]} rotation={[0.531, 0.443, -0.102]} scale={2.412} />
        <mesh name="Liquid_Domain002" geometry={nodes.Liquid_Domain002.geometry} material={materials['spilled soup_P']} position={[-0.232, 2.765, 1.552]} scale={[6.046, 9.07, 6.046]} />
        <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials.egg_P} position={[-1.213, 5.114, 0.33]} rotation={[1.675, 0.881, 0.415]} scale={[1.054, 1.097, 1.032]} />
        <mesh name="yolk" geometry={nodes.yolk.geometry} material={materials.yolk_P} position={[-1.094, 5.249, 0.077]} rotation={[1.675, 0.881, 0.415]} scale={[0.422, 0.405, 0.428]} />
        <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials.hashi_P} position={[0.583, 4.849, -0.728]} rotation={[0.646, -0.091, 0.283]} scale={0.067} />
        <mesh name="Cube003" geometry={nodes.Cube003.geometry} material={materials.hashi_P} position={[0.205, 4.963, -0.549]} rotation={[0.66, 0.21, 0.583]} scale={0.067} />
        <mesh name="seaweed" geometry={nodes.seaweed.geometry} material={materials.seaweed} position={[1.674, 2.834, 2.346]} rotation={[-1.023, 0.737, 0.996]} scale={0.622} />
        <mesh name="seaweed001" geometry={nodes.seaweed001.geometry} material={materials.seaweed} position={[1.698, 2.775, 2.219]} rotation={[-1.198, 0.7, 1.071]} scale={0.635} />
        <mesh name="white_thingy" geometry={nodes.white_thingy.geometry} material={materials.whitewhingy_P} position={[1.197, 4.389, 0.978]} rotation={[1.458, 0.864, -0.58]} scale={0.415} />
        <mesh name="white_thingy002" geometry={nodes.white_thingy002.geometry} material={materials.whitewhingy_P} position={[-0.895, 4.364, 1.79]} rotation={[-1.968, -0.496, -1.614]} scale={0.415} />
        <mesh name="onion_1" geometry={nodes.onion_1.geometry} material={materials.seaweed_P} position={[-1.059, 3.465, 2.911]} rotation={[0.19, -0.493, -0.496]} scale={[0.13, 0.04, 0.13]} />
        <mesh name="onion_2" geometry={nodes.onion_2.geometry} material={materials.seaweed_P} position={[0.927, 4.134, 3.266]} rotation={[0.17, -0.574, -0.836]} scale={[0.213, 0.043, 0.213]} />
        <mesh name="onion3_" geometry={nodes.onion3_.geometry} material={materials.seaweed_P} position={[1.713, 3.781, 3.337]} rotation={[-0.42, -0.172, -0.327]} scale={[0.213, 0.039, 0.213]} />
        <mesh name="Sphere" geometry={nodes.Sphere.geometry} material={materials.corn_P} position={[0.231, 4.122, 2.583]} rotation={[0.405, 0.129, 0.5]} scale={0.136} />
        <mesh name="Sphere001" geometry={nodes.Sphere001.geometry} material={materials.corn_P} position={[-0.187, 3.749, 3.103]} rotation={[-0.144, 0.217, -0.482]} scale={0.136} />
        <mesh name="Sphere002" geometry={nodes.Sphere002.geometry} material={materials.corn_P} position={[1.164, 3.338, 2.672]} rotation={[0.047, -0.018, 0.453]} scale={0.136} />
        <mesh name="Sphere003" geometry={nodes.Sphere003.geometry} material={materials.corn_P} position={[1.774, 3.79, 1.862]} rotation={[0.015, -0.658, 0.323]} scale={0.136} />
        <mesh name="Sphere004" geometry={nodes.Sphere004.geometry} material={materials.corn} position={[0.344, 3.412, 1.742]} rotation={[-0.565, 0.019, 1.375]} scale={0.136} />
        <mesh name="Sphere005" geometry={nodes.Sphere005.geometry} material={materials.corn_P} position={[-1.285, 3.495, 2.02]} rotation={[-1.408, -1.179, -2.264]} scale={0.136} />
        <mesh name="Sphere006" geometry={nodes.Sphere006.geometry} material={materials.corn_P} position={[-0.094, 3.202, 3.495]} rotation={[-0.042, 0.209, 0.84]} scale={0.136} />
        <mesh name="Sphere007" geometry={nodes.Sphere007.geometry} material={materials.corn_P} position={[0.707, 3.936, 4.042]} rotation={[-0.363, 0.315, 0.303]} scale={0.136} />
        <mesh name="Sphere008" geometry={nodes.Sphere008.geometry} material={materials.corn_P} position={[1.77, 3.832, 3.126]} rotation={[-0.642, 0.159, -0.426]} scale={0.136} />
        <mesh name="Sphere010" geometry={nodes.Sphere010.geometry} material={materials.corn_P} position={[-0.273, 3.467, 4.615]} rotation={[-0.504, 0.284, 0.654]} scale={0.136} />
        <mesh name="NODDLES_MAIN_BEZIER" geometry={nodes.NODDLES_MAIN_BEZIER.geometry} material={materials.noodles_P} position={[0.305, 2.715, 1.133]} rotation={[-2.861, -0.44, -3.112]} scale={0.517} />
        <mesh name="onion_2001" geometry={nodes.onion_2001.geometry} material={materials.seaweed_P} position={[-0.074, 3.768, 3.666]} rotation={[-1.017, -0.082, -2.298]} scale={[0.145, 0.03, 0.145]} />
        <mesh name="onion_1001" geometry={nodes.onion_1001.geometry} material={materials.seaweed_P} position={[1.325, 3.767, 2.041]} rotation={[0.789, 0.296, 0.472]} scale={[0.106, 0.033, 0.106]} />
        <mesh name="onion3_001" geometry={nodes.onion3_001.geometry} material={materials.seaweed_P} position={[-0.51, 4.57, 3.488]} rotation={[-0.42, -0.172, -0.327]} scale={[0.261, 0.048, 0.261]} />
      </group>
    </group>
  )
}

useGLTF.preload('/model.glb')
